import { chromium } from '@playwright/test';
import { mkdir, writeFile } from 'node:fs/promises';
import assert from 'node:assert/strict';

await mkdir('qa', { recursive: true });
const browser = await chromium.launch({ channel: 'msedge', headless: true });
const page = await browser.newPage({ viewport: { width: 1280, height: 1000 }, deviceScaleFactor: 1 });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
await page.goto('http://localhost:5179');
await page.locator('#sample-buttons button:enabled').first().waitFor({ timeout: 30000 });
assert.equal(await page.locator('#prediction-number').textContent(), '—');
await page.screenshot({ path: 'qa/desktop-empty.png', fullPage: true });
const samples = [];
for (let digit = 0; digit < 10; digit++) {
  await page.locator('#clear').click();
  await page.locator('#sample-buttons button').nth(digit).click();
  await page.waitForFunction(() => document.querySelector('#prediction-number').textContent !== '—');
  samples.push({ digit, prediction: await page.locator('#prediction-number').textContent() });
}
await page.locator('#sample-buttons button').nth(3).click();
await page.waitForTimeout(500);
assert.equal(await page.locator('.neighbor').count(), 6);
const initialOverlap = await page.locator('#overlap-title').textContent();
await page.locator('.neighbor').nth(2).click();
assert.equal(await page.locator('.neighbor').nth(2).getAttribute('aria-pressed'), 'true');
await page.getByRole('button', { name: '차이 보기', exact: true }).click();
assert.equal(await page.getByRole('button', { name: '차이 보기', exact: true }).getAttribute('aria-pressed'), 'true');
await page.getByRole('button', { name: '겹쳐 보기', exact: true }).click();
await page.screenshot({ path: 'qa/desktop-result.png', fullPage: true });
await page.locator('#clear').click();
assert.equal(await page.locator('#prediction-number').textContent(), '—');
const rect = await page.locator('#draw').boundingBox();
await page.mouse.move(rect.x + rect.width * .5, rect.y + rect.height * .2);
await page.mouse.down();
await page.mouse.move(rect.x + rect.width * .5, rect.y + rect.height * .8, { steps: 30 });
await page.waitForFunction(() => document.querySelector('#prediction-number').textContent !== '—');
assert.equal(await page.locator('#prediction-number').textContent(), '1');
await page.mouse.up();
await page.waitForFunction(() => document.querySelector('#prediction-number').textContent !== '—');
const drawnPrediction = await page.locator('#prediction-number').textContent();
assert.equal(drawnPrediction, '1');
await page.locator('#undo').click();
assert.equal(await page.locator('#prediction-number').textContent(), '—');
await page.locator('#redo').click();
await page.waitForFunction(() => document.querySelector('#prediction-number').textContent !== '—');
const downloadPromise = page.waitForEvent('download');
await page.locator('#save').click();
const download = await downloadPromise;
assert.equal(download.suggestedFilename(), 'digit-lab-handwriting.png');
const canvasInk = await page.locator('#comparison').evaluate(canvas => Array.from(canvas.getContext('2d').getImageData(0, 0, 28, 28).data).filter((v, i) => i % 4 !== 3 && v < 240).length);
assert.ok(canvasInk > 30);
const sizes = [];
for (const width of [375, 768, 1280]) {
  await page.setViewportSize({ width, height: 900 });
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth > innerWidth);
  assert.equal(overflow, false, `Overflow at ${width}`);
  await page.screenshot({ path: `qa/viewport-${width}.png`, fullPage: true });
  sizes.push({ width, overflow });
}
await page.locator('summary').click();
await page.screenshot({ path: 'qa/method-open.png', fullPage: true });
const mobile = await browser.newContext({ viewport: { width: 375, height: 812 }, hasTouch: true, isMobile: true });
const touchPage = await mobile.newPage();
await touchPage.goto('http://localhost:5179');
await touchPage.locator('#sample-buttons button:enabled').first().waitFor();
const box = await touchPage.locator('#draw').boundingBox();
await touchPage.touchscreen.tap(box.x + box.width / 2, box.y + box.height / 2);
await touchPage.waitForFunction(() => document.querySelector('#prediction-number').textContent !== '—');
assert.equal(await touchPage.locator('#canvas-hint').isVisible(), false);
assert.deepEqual(errors, []);
await writeFile('qa/report.json', JSON.stringify({ samples, drawnPrediction, canvasInk, initialOverlap, sizes, touch: true, errors }, null, 2));
console.log(JSON.stringify({ samples, drawnPrediction, canvasInk, sizes, touch: true, errors }));
await browser.close();
